# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lab5-AMAD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab5-AMAD
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
end
